### ISSUE TITLE
Can't autocomplete after using arrow keys?

### ISSUE THREAD

**Issue by max-sixty** [bodil/vscode-file-browser#35] opened 2022-11-05 21:21 UTC
Firstly @bodil,  thanks a lot for the awesome extension! Sorry to see it hasn't been updated in a while; I hope all is good on your end.

One minor issue I've had is that after navigating back a directory, I then can't use the autocomplete; here's a demo:

![Screen Cast 2022-11-05 at 2 17 28 PM](https://user-images.githubusercontent.com/5635139/200141716-87d5df6a-d71a-4e67-98bc-9354ec550327.gif)

Is this just me / is this expected?

(I tried to open an issue on @jeffgran's repo, but issues aren't available there)

Thank you!
Max

**Comment by max-sixty** [comment] 2022-11-05 23:14
After working with this for a couple of hours, I think this must be new behavior — I was so reliant on this — I hadn't realized quite how reliant when I wrote the issue this morning.

Assuming that's correct, do others see the same behavior? i.e. is it something that's changed in VSCode, or something on my system?

**Comment by bodil** [comment] 2022-11-05 23:45
I'm getting it too, at least on MacOS. Seems to be a VSCode regression. Not sure it can be fixed on this end but I'm going to look into it.

**Comment by max-sixty** [comment] 2022-11-06 00:07
Thank you @bodil !

**Closed as completed** 2022-11-19 10:32 UTC
