### ISSUE TITLE
File browser loses focus

### ISSUE THREAD

**Issue by victormamede** [bodil/vscode-file-browser#38] opened 2022-11-17 18:16 UTC
I don't know if this is expected or just a config, but when I change directory by typing the directory path - `../` or `folder/` - or using the shortcuts `stepIn`/`stepOut`, the text box loses focus and I have to click it to continue writing. This is really annoying and defeats the purpose for me.

**Comment by bodil** [comment] 2022-11-19 10:34
Duplicate of #35

**Closed as completed by bodil** 2022-11-19 10:34 UTC
